version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NUXT_PUBLIC_API_BASE=http://web:8000/api
      - HOST=0.0.0.0
    networks:
      - lokalise-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your-secret-key-here
      - LOKALISE_API_KEY=b6527880074de76eaf7e56c11a5992d099cdf543
      - LOKALISE_PROJECT_ID=2567109568819f583590a8.57930632
      - OPEN_ROUTER_API_KEY=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
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app
    networks:
      - lokalise-network
networks:
  lokalise-network:
    driver: bridge
